project:
  type: website

website:
  title: "Ankur Garg"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: research.qmd
        text: Research

      - href: teach.qmd
        text: Teaching

      - href: CV.qmd
        text: CV
    tools:
      - icon: github
        href: https://github.com/agarg7

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


